FROM maven:3.9-eclipse-temurin-17

WORKDIR /workspace/app

# Copy POM file first to cache Maven dependencies
COPY pom.xml .
# Download dependencies to cache them in Docker layer
RUN mvn dependency:go-offline

# Copy source code
COPY src src

CMD ["mvn", "test"] 